#WRITE A PROGRAM TO CREATE A COPY OF A LIST,
#REPALCE 10 TO ITs  FIRST AND LAST .THEN DISPLAY THE LISTS
a=[1,2,3,4,5,6,7,8,9]
b=a.copy()
b[0]=10
b[-1]=10
print('ORIGINAL LIST:',a)
print('NEW LIST:',b)
