'''EXTRACT TWO LIST SLICES OUT OF A GIVEN LIST OF NUMBERS ,DISPLAY AND PRINT THE SUM OF THE ELEMENTS OF FIRST LIST
SLICE WHICH CONTAIN EVERY OTHER  ELEMENT OF THE LIST BETWEEN INDEXES 5 TO 15.PROGRAM SHOULD ALSO DISPLAY
THE AVERAGE OF ELEMENTS IN SECOND LIST THAT CONTAINS EVERY FOURTH ELEMENT OF THE LIST.
THE GIVEN LIST CONTAINS NUMBERS FROM 1 TO 20   '''

LIST=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
print(LIST)
LIST1=LIST[5:15:2]
print('LIST1:',LIST1)
LIST2=LIST[::4]
print('LIST2:',LIST2)
sum1=0
sum2=0
for a in LIST1:
    sum1=sum1+a
print('sumof elements of LIST1',sum1)
for b in LIST2:
    sum2=sum2+b
print('sum of elements of LIST2',sum2)
print('average of elements of LIST2',sum2/len(LIST2))
